-- =============================================================================
-- Migration 0003: end-of-week quiz questions (Weeks 1–3)
-- =============================================================================
-- GENERATED by scripts/quiz-bank.mjs — edit the bank there and regenerate.
-- Idempotent: clears each weekly quiz's questions, then reseeds.
-- =============================================================================


-- Day 5
delete from public.quiz_questions where quiz_id = (select id from public.quizzes where day_id = (select id from public.program_days where day_number = 5) limit 1);
with q as (
  insert into public.quiz_questions (quiz_id, position, prompt, question_type, time_limit_seconds)
  select id, 1, 'What is Claude?', 'mc', 20 from public.quizzes
   where day_id = (select id from public.program_days where day_number = 5) limit 1
  returning id
)
insert into public.quiz_options (question_id, position, label, is_correct)
select q.id, v.pos, v.label, v.correct
from q, (values
      (1, 'A search engine that returns a list of links', false),
      (2, 'A robot that runs businesses on its own', false),
      (3, 'A social media app for founders', false),
      (4, 'An AI assistant made by Anthropic', true)
) as v(pos, label, correct);
with q as (
  insert into public.quiz_questions (quiz_id, position, prompt, question_type, time_limit_seconds)
  select id, 2, 'How does a large language model like Claude produce an answer?', 'mc', 25 from public.quizzes
   where day_id = (select id from public.program_days where day_number = 5) limit 1
  returning id
)
insert into public.quiz_options (question_id, position, label, is_correct)
select q.id, v.pos, v.label, v.correct
from q, (values
      (1, 'It looks the answer up in a single fact database', false),
      (2, 'A human types the reply in real time', false),
      (3, 'It copies the first website it finds', false),
      (4, 'It predicts likely next words based on patterns learned from lots of text', true)
) as v(pos, label, correct);
with q as (
  insert into public.quiz_questions (quiz_id, position, prompt, question_type, time_limit_seconds)
  select id, 3, 'Claude gives you a confident-sounding market statistic. It''s fine to put it straight into your pitch deck.', 'tf', 20 from public.quizzes
   where day_id = (select id from public.program_days where day_number = 5) limit 1
  returning id
)
insert into public.quiz_options (question_id, position, label, is_correct)
select q.id, v.pos, v.label, v.correct
from q, (values
      (1, 'True', false),
      (2, 'False', true)
) as v(pos, label, correct);
with q as (
  insert into public.quiz_questions (quiz_id, position, prompt, question_type, time_limit_seconds)
  select id, 4, 'Which prompt will get the most useful business ideas?', 'mc', 30 from public.quizzes
   where day_id = (select id from public.program_days where day_number = 5) limit 1
  returning id
)
insert into public.quiz_options (question_id, position, label, is_correct)
select q.id, v.pos, v.label, v.correct
from q, (values
      (1, '"Give me a business idea."', false),
      (2, '"Make me rich."', false),
      (3, '"Business ideas pls"', false),
      (4, '"You''re a startup coach. I''m 16, in NYC, love sneakers, and have $200. Give me 5 ideas that solve a real problem for teens, who pays, and why."', true)
) as v(pos, label, correct);
with q as (
  insert into public.quiz_questions (quiz_id, position, prompt, question_type, time_limit_seconds)
  select id, 5, 'Your prompt keeps returning generic ideas. What''s the most effective fix?', 'mc', 25 from public.quizzes
   where day_id = (select id from public.program_days where day_number = 5) limit 1
  returning id
)
insert into public.quiz_options (question_id, position, label, is_correct)
select q.id, v.pos, v.label, v.correct
from q, (values
      (1, 'Send the exact same prompt again', false),
      (2, 'Rewrite it in ALL CAPS', false),
      (3, 'Make it as short as possible', false),
      (4, 'Add context: who you are, the customer, your constraints, and the format you want', true)
) as v(pos, label, correct);
with q as (
  insert into public.quiz_questions (quiz_id, position, prompt, question_type, time_limit_seconds)
  select id, 6, 'What''s the strongest starting point for a startup?', 'mc', 25 from public.quizzes
   where day_id = (select id from public.program_days where day_number = 5) limit 1
  returning id
)
insert into public.quiz_options (question_id, position, label, is_correct)
select q.id, v.pos, v.label, v.correct
from q, (values
      (1, 'A great name and logo', false),
      (2, 'A cool technology looking for a use', false),
      (3, 'An idea you''re sure has no competitors (without checking)', false),
      (4, 'A frustrating problem you''ve seen real people struggle with', true)
) as v(pos, label, correct);
with q as (
  insert into public.quiz_questions (quiz_id, position, prompt, question_type, time_limit_seconds)
  select id, 7, 'A founder asks Claude to write fake 5-star reviews for launch day. Best response?', 'mc', 25 from public.quizzes
   where day_id = (select id from public.program_days where day_number = 5) limit 1
  returning id
)
insert into public.quiz_options (question_id, position, label, is_correct)
select q.id, v.pos, v.label, v.correct
from q, (values
      (1, 'Fine, because the AI wrote them, not the founder', false),
      (2, 'Fine if it''s fewer than 10 reviews', false),
      (3, 'Fine, as long as the product is actually good', false),
      (4, 'Don''t — it deceives customers and can break the law and platform rules', true)
) as v(pos, label, correct);
with q as (
  insert into public.quiz_questions (quiz_id, position, prompt, question_type, time_limit_seconds)
  select id, 8, 'Which of these should you NOT paste into an AI tool?', 'mc', 20 from public.quizzes
   where day_id = (select id from public.program_days where day_number = 5) limit 1
  returning id
)
insert into public.quiz_options (question_id, position, label, is_correct)
select q.id, v.pos, v.label, v.correct
from q, (values
      (1, 'A public news article about your industry', false),
      (2, 'Your pitch deck outline', false),
      (3, 'A rough draft of your own business idea', false),
      (4, 'Customers'' personal info (names, phone numbers) without their permission', true)
) as v(pos, label, correct);
with q as (
  insert into public.quiz_questions (quiz_id, position, prompt, question_type, time_limit_seconds)
  select id, 9, 'Claude says your ideal customer is "busy moms." What''s the best founder move?', 'mc', 25 from public.quizzes
   where day_id = (select id from public.program_days where day_number = 5) limit 1
  returning id
)
insert into public.quiz_options (question_id, position, label, is_correct)
select q.id, v.pos, v.label, v.correct
from q, (values
      (1, 'Re-ask Claude until it gives a different answer', false),
      (2, 'Stop using AI for customer research entirely', false),
      (3, 'Accept it — AI has seen more data than you', false),
      (4, 'Treat it as a hypothesis and test it by talking to real people', true)
) as v(pos, label, correct);
with q as (
  insert into public.quiz_questions (quiz_id, position, prompt, question_type, time_limit_seconds)
  select id, 10, 'Using Claude as a "thought partner" means…', 'mc', 20 from public.quizzes
   where day_id = (select id from public.program_days where day_number = 5) limit 1
  returning id
)
insert into public.quiz_options (question_id, position, label, is_correct)
select q.id, v.pos, v.label, v.correct
from q, (values
      (1, 'Claude replaces talking to customers', false),
      (2, 'Claude does the work so you don''t have to understand it', false),
      (3, 'Claude makes the key decisions for you', false),
      (4, 'You make the decisions; Claude helps you generate options, critique and draft', true)
) as v(pos, label, correct);
with q as (
  insert into public.quiz_questions (quiz_id, position, prompt, question_type, time_limit_seconds)
  select id, 11, 'Why do founders map their strengths early on?', 'mc', 20 from public.quizzes
   where day_id = (select id from public.program_days where day_number = 5) limit 1
  returning id
)
insert into public.quiz_options (question_id, position, label, is_correct)
select q.id, v.pos, v.label, v.correct
from q, (values
      (1, 'To decide who deserves the prize', false),
      (2, 'Because investors only fund one skill', false),
      (3, 'So everyone does the same job', false),
      (4, 'So roles cover what the business needs and gaps are obvious', true)
) as v(pos, label, correct);
with q as (
  insert into public.quiz_questions (quiz_id, position, prompt, question_type, time_limit_seconds)
  select id, 12, 'An entrepreneur''s core job is to…', 'mc', 20 from public.quizzes
   where day_id = (select id from public.program_days where day_number = 5) limit 1
  returning id
)
insert into public.quiz_options (question_id, position, label, is_correct)
select q.id, v.pos, v.label, v.correct
from q, (values
      (1, 'Build the product without talking to anyone', false),
      (2, 'Have the most original idea in the world', false),
      (3, 'Raise as much money as possible first', false),
      (4, 'Find a real problem and build a solution people will pay for', true)
) as v(pos, label, correct);

-- Day 10
delete from public.quiz_questions where quiz_id = (select id from public.quizzes where day_id = (select id from public.program_days where day_number = 10) limit 1);
with q as (
  insert into public.quiz_questions (quiz_id, position, prompt, question_type, time_limit_seconds)
  select id, 1, 'The Business Model Canvas is…', 'mc', 20 from public.quizzes
   where day_id = (select id from public.program_days where day_number = 10) limit 1
  returning id
)
insert into public.quiz_options (question_id, position, label, is_correct)
select q.id, v.pos, v.label, v.correct
from q, (values
      (1, 'A tool for designing a logo', false),
      (2, 'A 40-page business plan', false),
      (3, 'A spreadsheet of monthly expenses', false),
      (4, 'A one-page map of how a business creates, delivers and captures value', true)
) as v(pos, label, correct);
with q as (
  insert into public.quiz_questions (quiz_id, position, prompt, question_type, time_limit_seconds)
  select id, 2, 'Which canvas block answers "Who are we creating value for?"', 'mc', 20 from public.quizzes
   where day_id = (select id from public.program_days where day_number = 10) limit 1
  returning id
)
insert into public.quiz_options (question_id, position, label, is_correct)
select q.id, v.pos, v.label, v.correct
from q, (values
      (1, 'Key Resources', false),
      (2, 'Cost Structure', false),
      (3, 'Key Partners', false),
      (4, 'Customer Segments', true)
) as v(pos, label, correct);
with q as (
  insert into public.quiz_questions (quiz_id, position, prompt, question_type, time_limit_seconds)
  select id, 3, 'The Value Proposition block describes…', 'mc', 20 from public.quizzes
   where day_id = (select id from public.program_days where day_number = 10) limit 1
  returning id
)
insert into public.quiz_options (question_id, position, label, is_correct)
select q.id, v.pos, v.label, v.correct
from q, (values
      (1, 'Who your investors are', false),
      (2, 'Your company''s mission statement', false),
      (3, 'How much the product costs to make', false),
      (4, 'Why customers choose you — the problem you solve or the gain you create', true)
) as v(pos, label, correct);
with q as (
  insert into public.quiz_questions (quiz_id, position, prompt, question_type, time_limit_seconds)
  select id, 4, 'The Channels block describes…', 'mc', 20 from public.quizzes
   where day_id = (select id from public.program_days where day_number = 10) limit 1
  returning id
)
insert into public.quiz_options (question_id, position, label, is_correct)
select q.id, v.pos, v.label, v.correct
from q, (values
      (1, 'Where you get your supplies', false),
      (2, 'The tools your team uses internally', false),
      (3, 'Your social media follower count', false),
      (4, 'How you reach customers and deliver the product to them', true)
) as v(pos, label, correct);
with q as (
  insert into public.quiz_questions (quiz_id, position, prompt, question_type, time_limit_seconds)
  select id, 5, 'The Revenue Streams block describes…', 'mc', 20 from public.quizzes
   where day_id = (select id from public.program_days where day_number = 10) limit 1
  returning id
)
insert into public.quiz_options (question_id, position, label, is_correct)
select q.id, v.pos, v.label, v.correct
from q, (values
      (1, 'Which partners you work with', false),
      (2, 'Every cost the business pays', false),
      (3, 'How fast the company is growing', false),
      (4, 'How the business earns money from each customer segment', true)
) as v(pos, label, correct);
with q as (
  insert into public.quiz_questions (quiz_id, position, prompt, question_type, time_limit_seconds)
  select id, 6, 'Which is the strongest Ideal Customer Profile?', 'mc', 25 from public.quizzes
   where day_id = (select id from public.program_days where day_number = 10) limit 1
  returning id
)
insert into public.quiz_options (question_id, position, label, is_correct)
select q.id, v.pos, v.label, v.correct
from q, (values
      (1, 'Everyone who wants to learn', false),
      (2, 'People who like technology', false),
      (3, 'Students', false),
      (4, 'NYC high school juniors in AP classes who study 2+ hrs a night and already pay for study apps', true)
) as v(pos, label, correct);
with q as (
  insert into public.quiz_questions (quiz_id, position, prompt, question_type, time_limit_seconds)
  select id, 7, 'Why is "everyone" a weak target customer for a new startup?', 'mc', 25 from public.quizzes
   where day_id = (select id from public.program_days where day_number = 10) limit 1
  returning id
)
insert into public.quiz_options (question_id, position, label, is_correct)
select q.id, v.pos, v.label, v.correct
from q, (values
      (1, 'Because everyone already has the product', false),
      (2, 'It''s actually the best target', false),
      (3, 'Investors don''t allow it', false),
      (4, 'You can''t reach, message or build for everyone — focus wins your first customers', true)
) as v(pos, label, correct);
with q as (
  insert into public.quiz_questions (quiz_id, position, prompt, question_type, time_limit_seconds)
  select id, 8, 'Lemonade stand: you sell 50 cups at $2. Each cup costs $0.50 to make, and your sign cost $20. What''s your profit?', 'mc', 35 from public.quizzes
   where day_id = (select id from public.program_days where day_number = 10) limit 1
  returning id
)
insert into public.quiz_options (question_id, position, label, is_correct)
select q.id, v.pos, v.label, v.correct
from q, (values
      (1, '$45', false),
      (2, '$100', false),
      (3, '$75', false),
      (4, '$55', true)
) as v(pos, label, correct);
with q as (
  insert into public.quiz_questions (quiz_id, position, prompt, question_type, time_limit_seconds)
  select id, 9, 'Lemonade stand: a cup sells for $2 and costs $0.50 to make. What''s the gross margin per cup?', 'mc', 25 from public.quizzes
   where day_id = (select id from public.program_days where day_number = 10) limit 1
  returning id
)
insert into public.quiz_options (question_id, position, label, is_correct)
select q.id, v.pos, v.label, v.correct
from q, (values
      (1, '$2.50', false),
      (2, '$0.50', false),
      (3, '$1.00', false),
      (4, '$1.50', true)
) as v(pos, label, correct);
with q as (
  insert into public.quiz_questions (quiz_id, position, prompt, question_type, time_limit_seconds)
  select id, 10, 'The main job of an early prototype is to…', 'mc', 25 from public.quizzes
   where day_id = (select id from public.program_days where day_number = 10) limit 1
  returning id
)
insert into public.quiz_options (question_id, position, label, is_correct)
select q.id, v.pos, v.label, v.correct
from q, (values
      (1, 'Be polished enough to sell to thousands of people', false),
      (2, 'Impress judges with design', false),
      (3, 'Replace the need for customer feedback', false),
      (4, 'Test your riskiest assumption quickly and cheaply with real users', true)
) as v(pos, label, correct);
with q as (
  insert into public.quiz_questions (quiz_id, position, prompt, question_type, time_limit_seconds)
  select id, 11, 'What does MVP stand for?', 'mc', 20 from public.quizzes
   where day_id = (select id from public.program_days where day_number = 10) limit 1
  returning id
)
insert into public.quiz_options (question_id, position, label, is_correct)
select q.id, v.pos, v.label, v.correct
from q, (values
      (1, 'Maximum Value Proposition', false),
      (2, 'Most Valuable Player', false),
      (3, 'Minimum Visual Prototype', false),
      (4, 'Minimum Viable Product', true)
) as v(pos, label, correct);
with q as (
  insert into public.quiz_questions (quiz_id, position, prompt, question_type, time_limit_seconds)
  select id, 12, 'You should finish building the full product before showing it to anyone.', 'tf', 20 from public.quizzes
   where day_id = (select id from public.program_days where day_number = 10) limit 1
  returning id
)
insert into public.quiz_options (question_id, position, label, is_correct)
select q.id, v.pos, v.label, v.correct
from q, (values
      (1, 'True', false),
      (2, 'False', true)
) as v(pos, label, correct);

-- Day 15
delete from public.quiz_questions where quiz_id = (select id from public.quizzes where day_id = (select id from public.program_days where day_number = 15) limit 1);
with q as (
  insert into public.quiz_questions (quiz_id, position, prompt, question_type, time_limit_seconds)
  select id, 1, 'TAM stands for Total Addressable Market. It means…', 'mc', 25 from public.quizzes
   where day_id = (select id from public.program_days where day_number = 15) limit 1
  returning id
)
insert into public.quiz_options (question_id, position, label, is_correct)
select q.id, v.pos, v.label, v.correct
from q, (values
      (1, 'The customers you''ll win this year', false),
      (2, 'Your total monthly revenue', false),
      (3, 'The number of competitors in your space', false),
      (4, 'Total demand for the product if you captured 100% of the market', true)
) as v(pos, label, correct);
with q as (
  insert into public.quiz_questions (quiz_id, position, prompt, question_type, time_limit_seconds)
  select id, 2, 'SAM (Serviceable Addressable Market) is…', 'mc', 25 from public.quizzes
   where day_id = (select id from public.program_days where day_number = 15) limit 1
  returning id
)
insert into public.quiz_options (question_id, position, label, is_correct)
select q.id, v.pos, v.label, v.correct
from q, (values
      (1, 'Every person on Earth', false),
      (2, 'The market your competitor owns', false),
      (3, 'Your revenue after costs', false),
      (4, 'The part of TAM you can actually serve with your product, channels and location', true)
) as v(pos, label, correct);
with q as (
  insert into public.quiz_questions (quiz_id, position, prompt, question_type, time_limit_seconds)
  select id, 3, 'SOM (Serviceable Obtainable Market) is…', 'mc', 25 from public.quizzes
   where day_id = (select id from public.program_days where day_number = 15) limit 1
  returning id
)
insert into public.quiz_options (question_id, position, label, is_correct)
select q.id, v.pos, v.label, v.correct
from q, (values
      (1, 'The price of your product', false),
      (2, 'The same as TAM', false),
      (3, 'The number of investors interested', false),
      (4, 'The share of SAM you can realistically capture in the near term', true)
) as v(pos, label, correct);
with q as (
  insert into public.quiz_questions (quiz_id, position, prompt, question_type, time_limit_seconds)
  select id, 4, 'Bottom-up sizing: 30,000 target customers × $60 per customer per year = ?', 'mc', 30 from public.quizzes
   where day_id = (select id from public.program_days where day_number = 15) limit 1
  returning id
)
insert into public.quiz_options (question_id, position, label, is_correct)
select q.id, v.pos, v.label, v.correct
from q, (values
      (1, '$180,000', false),
      (2, '$18 million', false),
      (3, '$600,000', false),
      (4, '$1.8 million', true)
) as v(pos, label, correct);
with q as (
  insert into public.quiz_questions (quiz_id, position, prompt, question_type, time_limit_seconds)
  select id, 5, 'Why do judges trust bottom-up market sizing more than "we just need 1% of a $10B market"?', 'mc', 25 from public.quizzes
   where day_id = (select id from public.program_days where day_number = 15) limit 1
  returning id
)
insert into public.quiz_options (question_id, position, label, is_correct)
select q.id, v.pos, v.label, v.correct
from q, (values
      (1, 'Bigger numbers always look better', false),
      (2, 'Top-down sizing is illegal', false),
      (3, 'It doesn''t need any research', false),
      (4, 'It''s built from real customer counts and prices, so it''s believable', true)
) as v(pos, label, correct);
with q as (
  insert into public.quiz_questions (quiz_id, position, prompt, question_type, time_limit_seconds)
  select id, 6, 'Which of these is PRIMARY research?', 'mc', 20 from public.quizzes
   where day_id = (select id from public.program_days where day_number = 15) limit 1
  returning id
)
insert into public.quiz_options (question_id, position, label, is_correct)
select q.id, v.pos, v.label, v.correct
from q, (values
      (1, 'Asking Claude to summarize a market', false),
      (2, 'Reading an industry report', false),
      (3, 'Googling market statistics', false),
      (4, 'Interviewing 10 potential customers yourself', true)
) as v(pos, label, correct);
with q as (
  insert into public.quiz_questions (quiz_id, position, prompt, question_type, time_limit_seconds)
  select id, 7, 'Revenue = ?', 'mc', 20 from public.quizzes
   where day_id = (select id from public.program_days where day_number = 15) limit 1
  returning id
)
insert into public.quiz_options (question_id, position, label, is_correct)
select q.id, v.pos, v.label, v.correct
from q, (values
      (1, 'Number of customers ÷ price', false),
      (2, 'Costs + profit − price', false),
      (3, 'Price − cost', false),
      (4, 'Price × number of units sold', true)
) as v(pos, label, correct);
with q as (
  insert into public.quiz_questions (quiz_id, position, prompt, question_type, time_limit_seconds)
  select id, 8, 'Profit = ?', 'mc', 20 from public.quizzes
   where day_id = (select id from public.program_days where day_number = 15) limit 1
  returning id
)
insert into public.quiz_options (question_id, position, label, is_correct)
select q.id, v.pos, v.label, v.correct
from q, (values
      (1, 'Price × customers', false),
      (2, 'Costs − revenue', false),
      (3, 'Revenue + costs', false),
      (4, 'Revenue − costs', true)
) as v(pos, label, correct);
with q as (
  insert into public.quiz_questions (quiz_id, position, prompt, question_type, time_limit_seconds)
  select id, 9, 'Which is value-based pricing?', 'mc', 25 from public.quizzes
   where day_id = (select id from public.program_days where day_number = 15) limit 1
  returning id
)
insert into public.quiz_options (question_id, position, label, is_correct)
select q.id, v.pos, v.label, v.correct
from q, (values
      (1, 'Copying a competitor''s price exactly', false),
      (2, 'Always being the cheapest option', false),
      (3, 'Cost to make it plus a fixed markup', false),
      (4, 'Pricing based on how much the problem is worth to the customer', true)
) as v(pos, label, correct);
with q as (
  insert into public.quiz_questions (quiz_id, position, prompt, question_type, time_limit_seconds)
  select id, 10, 'Each unit costs you $4 to make and you want a 60% gross margin. What should you charge?', 'mc', 40 from public.quizzes
   where day_id = (select id from public.program_days where day_number = 15) limit 1
  returning id
)
insert into public.quiz_options (question_id, position, label, is_correct)
select q.id, v.pos, v.label, v.correct
from q, (values
      (1, '$2.40', false),
      (2, '$8', false),
      (3, '$6.40', false),
      (4, '$10', true)
) as v(pos, label, correct);
with q as (
  insert into public.quiz_questions (quiz_id, position, prompt, question_type, time_limit_seconds)
  select id, 11, 'Fixed costs are $500 and you make $5 profit on each unit. How many units to break even?', 'mc', 30 from public.quizzes
   where day_id = (select id from public.program_days where day_number = 15) limit 1
  returning id
)
insert into public.quiz_options (question_id, position, label, is_correct)
select q.id, v.pos, v.label, v.correct
from q, (values
      (1, '500', false),
      (2, '2,500', false),
      (3, '50', false),
      (4, '100', true)
) as v(pos, label, correct);
with q as (
  insert into public.quiz_questions (quiz_id, position, prompt, question_type, time_limit_seconds)
  select id, 12, 'CAC stands for…', 'mc', 20 from public.quizzes
   where day_id = (select id from public.program_days where day_number = 15) limit 1
  returning id
)
insert into public.quiz_options (question_id, position, label, is_correct)
select q.id, v.pos, v.label, v.correct
from q, (values
      (1, 'Company Asset Count', false),
      (2, 'Cash After Costs', false),
      (3, 'Customer Annual Commitment', false),
      (4, 'Customer Acquisition Cost', true)
) as v(pos, label, correct);
with q as (
  insert into public.quiz_questions (quiz_id, position, prompt, question_type, time_limit_seconds)
  select id, 13, 'Which go-to-market plan is strongest for your first 100 customers?', 'mc', 30 from public.quizzes
   where day_id = (select id from public.program_days where day_number = 15) limit 1
  returning id
)
insert into public.quiz_options (question_id, position, label, is_correct)
select q.id, v.pos, v.label, v.correct
from q, (values
      (1, 'Build it and people will find it', false),
      (2, 'Go viral on TikTok', false),
      (3, 'Run a Super Bowl ad', false),
      (4, 'Partner with 3 school clubs, demo at their meetings, offer a free first month, track sign-ups weekly', true)
) as v(pos, label, correct);
